version: '1'

services:
  mic-eureka:
    build:
      context: eureka
    image: mic-eureka:latest
    ports:
      - 8761:8761

  mic-gateway:
    build:
      context: gateway
    image: mic-gateway:latest
    links:
      - mic-eureka
      - mic-user
      - mic-email
    ports:
      - 8769:8769

  mic-user:
    build:
      context: user-service
    image: mic-user:latest

  mic-email:
    build:
      context: email-service
    image: mic-email:latest