apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  labels:
    name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka  #pod标签
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: hjq1015/mic-eureka:latest
        #posts:
        #    - containerPort: 8761
---
kind: Service
apiVersion: v1
metadata:
  name: eureka
spec:
  selector:
    node: eureka
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 32111
  type: NodePort